module13/lesson01_django/instagram/app_instagram/urls.py
from django.urls import path

from . import views

app_name = "app_instagram"

urlpatterns = [
    path("", views.main, name="main"),
    path("upload/", views.upload, name="upload"),
    path("pictures/", views.pictures, name="pictures"),
    path("pictures/remove/<int:pic_id>", views.remove_picture, name="remove"),
    path("pictures/edit/<int:pic_id>", views.edit_picture, name="edit")
]

module13/lesson01_django/instagram/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_instagram.urls")),
    path('users/', include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

module13/lesson01_django/instagram/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                     authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

module13/lesson01_django/instagram/app_instagram/models.py
import os
from uuid import uuid4

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

def update_filename(instance, filename):
    upload_to = 'uploads'
    ext = filename.split('.')[-1]
    filename = f"{uuid4().hex}.{ext}"
    return os.path.join(upload_to, filename)


class Picture(models.Model):
    description = models.CharField(max_length=350)
    path = models.ImageField(upload_to=update_filename)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.user}: {self.path}"

module13/lesson01_django/instagram/app_instagram/forms.py
from django.forms import ModelForm, ImageField, FileInput, CharField, TextInput

from .models import Picture


class PictureForm(ModelForm):
    description = CharField(max_length=350, widget=TextInput(attrs={"class": "form-control"}))
    path = ImageField(widget=FileInput(attrs={"class": "form-control"}))

    class Meta:
        model = Picture
        fields = ['description', 'path']

module13/lesson01_django/instagram/app_instagram/views.py
import os

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import PictureForm
from .models import Picture


# Create your views here.


def main(request):
    return render(request, "app_instagram/index.html", context={"title": "Killer Instagram"})


@login_required
def upload(request):
    form = PictureForm(instance=Picture())
    if request.method == "POST":
        form = PictureForm(request.POST, request.FILES, instance=Picture())
        if form.is_valid():
            pic = form.save(commit=False)
            pic.user = request.user
            pic.save()
            return redirect(to="app_instagram:pictures")

    return render(request, "app_instagram/upload.html", context={"title": "Killer Instagram", "form": form})


@login_required
def pictures(request):
    pictures = Picture.objects.filter(user=request.user).all()  # noqa
    return render(request, "app_instagram/pictures.html", context={"title": "Killer Instagram", "pictures": pictures})


@login_required
def remove_picture(request, pic_id):
    pic = Picture.objects.filter(pk=pic_id, user=request.user)
    try:
        os.unlink(os.path.join(settings.MEDIA_ROOT, str(pic.first().path)))
    except OSError as e:
        print(e)
    pic.delete()
    return redirect(to="app_instagram:pictures")


@login_required
def edit_picture(request, pic_id):
    if request.method == "POST":
        description = request.POST["description"]
        Picture.objects.filter(pk=pic_id, user=request.user).update(description=description)
        return redirect(to="app_instagram:pictures")

    picture = Picture.objects.filter(pk=pic_id, user=request.user).first()
    ctx = {"title": "Killer Instagram", "picture": picture}
    return render(request, "app_instagram/edit.html", context=ctx)

module13/lesson01_django/instagram/app_instagram/templates/app_instagram/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_instagram:pictures' %}">Pictures</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_instagram:upload' %}">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Create account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

module13/lesson01_django/instagram/app_instagram/templates/app_instagram/edit.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Edit your picture</h1>
<form action="{% url 'app_instagram:edit' picture.id %}" method="post">
  {% csrf_token %}
  <img src="/media/{{picture.path}}" class="card-img-top" alt="...">
  <div class="mb-3">
    <label class="form-label">Опис файлу</label>
    <input type="text" class="form-control" value="{{picture.description}}" name="description">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

module13/lesson01_django/instagram/app_instagram/templates/app_instagram/index.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Killer Instagram</h1>
{% endblock %}

module13/lesson01_django/instagram/app_instagram/templates/app_instagram/pictures.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Your pictures</h1>
<div class="row">
    {% for picture in pictures %}
    <div class="col-md-4">
        <div class="card col-md-4" style="width: 18rem;">
            <img src="/media/{{picture.path}}" class="card-img-top" alt="...">
            <div class="card-body">
<!--                <h5 class="card-title">{{picture.path}}</h5>-->
                <p class="card-text">
                    {{picture.description}}
                </p>
                <a href="{% url 'app_instagram:edit' picture.id %}" class="btn btn-warning">Edit</a>
                <a href="{% url 'app_instagram:remove' picture.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>

    </div>

    {% endfor %}
</div>
{% endblock %}

module13/lesson01_django/instagram/app_instagram/templates/app_instagram/upload.html
{% extends "app_instagram/base.html" %}

{% block content %}
<h1>Upload file</h1>
<form action="{% url 'app_instagram:upload' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Опис файлу</label>
    {{ form.description }}
  </div>
  <div class="mb-3">
    <label class="form-label">Файл</label>
    {{ form.path }}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}